### ISSUE TITLE
Failed to start it :( - see the screenshot. I'm using latest version of vscode

### ISSUE THREAD

**Issue by dragos199993** [alexcambose/time-tracker#1]
![image](https://user-images.githubusercontent.com/22987936/46882634-0ae4a280-ce58-11e8-9a39-f28be36ebe66.png)

**Comment by 0ly** [comment]
Same issue.

Using VSC Version 1.28 installed on macOS 10.14

Here's an additional screenshot with dev tools opened (after clicking "Start Work Session!"):

![image](https://user-images.githubusercontent.com/10458787/47625801-c155b200-dafd-11e8-8cb7-2d6e305f0103.png)

**Comment by alexcambose** [comment]
Should be fixed now
